export const caseData = [
    {
      caseID: 'CA103210',
      caseType: 'Balance Bill',
      stepID: 'ST637',
      task: 'Examine Claim & Add Attorney',
      targetDate: '06-10-2024',
      priority: 'Medium',
      status: 'Not Started',
    },
    {
      caseID: 'CA301450',
      caseType: 'Payment Concerns',
      stepID: 'ST901',
      task: 'Documentation Approval',
      targetDate: '06-10-2024',
      priority: 'High',
      status: 'In Progress',
    },
    {
      caseID: 'CA200121',
      caseType: 'Request for Quote',
      stepID: 'ST117',
      task: 'Contract Negotiation',
      targetDate: '06-14-2024',
      priority: 'Low',
      status: 'Blocked',
    },
    {
      caseID: 'CA200121',
      caseType: 'Request for Quote',
      stepID: 'ST117',
      task: 'Contract Negotiation',
      targetDate: '06-14-2024',
      priority: 'Low',
      status: 'Blocked',
    },
    {
      caseID: 'CA200121',
      caseType: 'Request for Quote',
      stepID: 'ST117',
      task: 'Contract Negotiation',
      targetDate: '06-14-2024',
      priority: 'Low',
      status: 'Blocked',
    },
    {
      caseID: 'CA200121',
      caseType: 'Request for Quote',
      stepID: 'ST117',
      task: 'Contract Negotiation',
      targetDate: '06-14-2024',
      priority: 'Low',
      status: 'Blocked',
    },
    {
      caseID: 'CA200121',
      caseType: 'Request for Quote',
      stepID: 'ST117',
      task: 'Contract Negotiation',
      targetDate: '06-14-2024',
      priority: 'Low',
      status: 'Blocked',
    },
    // Add more data as needed
  ];
  
  export const watchlistData = [
    {
      caseID: 'CA301230',
      priority: 'High',
      status: 'Processing',
      assignee: 'Tim Butler',
      slaStatus: 'Late',
    },
    {
      caseID: 'CA108360',
      priority: 'Highest',
      status: 'Settlement Offer Sent',
      assignee: 'Steve Smith',
      slaStatus: 'At Risk',
    },
    {
      caseID: 'CA301090',
      priority: 'Medium',
      status: 'In Processing',
      assignee: 'Rocky True',
      slaStatus: 'At Risk',
    },
    {
        caseID: 'CA108360',
        priority: 'Highest',
        status: 'Settlement Offer Sent',
        assignee: 'Steve Smith',
        slaStatus: 'At Risk',
      },
      {
        caseID: 'CA108360',
        priority: 'Highest',
        status: 'Settlement Offer Sent',
        assignee: 'Steve Smith',
        slaStatus: 'At Risk',
      },
      {
        caseID: 'CA108360',
        priority: 'Highest',
        status: 'Settlement Offer Sent',
        assignee: 'Steve Smith',
        slaStatus: 'At Risk',
      },
      {
        caseID: 'CA108360',
        priority: 'Highest',
        status: 'Settlement Offer Sent',
        assignee: 'Steve Smith',
        slaStatus: 'At Risk',
      },
    // Add more watchlist data
  ];
  