const resList = [
    {
        id: 1,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 4,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 2,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 3.4,
        maxDeliveryTime: 30,
        openedTill: "12:30 AM",
        priceForTwo: "$1100",
    },
    {
        id: 3,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 4,
        maxDeliveryTime: 30,
        openedTill: "11:00 AM",
        priceForTwo: "$1400",
    },
    {
        id: 4,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 2.4,
        maxDeliveryTime: 30,
        openedTill: "11:00 PM",
        priceForTwo: "$1140",
    },
    {
        id: 5,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 3.2,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 6,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 3.9,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 7,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 3.4,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 8,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 3.4,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 9,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 4,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 10,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 3.6,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 11,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 2.4,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 12,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 3.3,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 13,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 4,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 14,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 4.3,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 15,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 4.1,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 16,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 3.3,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 17,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 2.5,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 18,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 3.8,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 19,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 3.6,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 20,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 3.9,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
    {
        id: 21,
        name: "Milan",
        location: "Sector-10, Faridabad Haryana, 121004",
        distanceFromCurrentLocation: "1.4 km",
        rating: 4,
        maxDeliveryTime: 30,
        openedTill: "12 noon",
        priceForTwo: "$1200",
    },
];

export default resList;